'use strict';
// Declare app level module which depends on views, and components
angular.module('ng02SlowControlApp', [
    'ngRoute',
    'home',
    'bellegarde',
    'cachedhist',
    'comissioning',
    'crptemps',
    'cryogenics',
    'cryostat',
    'floor',
    'gauges',
    'groundplanes',
    'histogram',
    'histogramvd',
    'histogramaverage',
    'histogramrange',
    'inside',
    'insidelayout',
    'jura',
    'lausanne',
    'lems',
    'links',
    'multiplexer',
    'pds',
    'purity',
    'saleve',
    'straingaugeshist',
    'tinternal',
    'underfloor',
    'zmonitor',
    'coldbox',
    'vdcontrol',
    'pl506',
    'vdcam',
    'testpage'
]);